version: '3'

services:
  todolist:
    container_name: TodoListContainer
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: on-failure
